### ISSUE TITLE
Upload Amazon S3

### ISSUE THREAD

**Issue by wilsonfalai** [yiidoc/yii2-redactor#14]
How can I do to upload to Amazon S3. I use a component in my system to upload to s3 and would like to use it on yii2redactor component

S3 component:
https://github.com/2amigos/yii2-resource-manager-component

Can you help me?

**Comment by zinzinday** [comment]
Hi,
You can do that.
Please refer http://imperavi.com/redactor/examples/s3/
Please create pull request implement into repo
Thanks
