### ISSUE TITLE
Caret position after images and videos insert

### ISSUE THREAD

**Issue by the0rist** [yiidoc/yii2-redactor#26]
Hi.
Every time when I insert picture or video in redactor, the caret stays on the same place where was before. Is it possible to fix it so the caret will be after inserted element? 

P.S. Sorry for my english.

**Comment by zinzinday** [comment]
I really can't imagine how your problem? Can you capture a screenshot of the problem?

**Comment by the0rist** [comment]
Here are the screenshots showing the problem.


​
I hope these screenshots will be helpful and I hope also you understand the
problem now.
Thank you and have a nice day.

2015-05-13 23:32 GMT+03:00 Nghia Nguyen <notifications@github.com>:

**Comment by zinzinday** [comment]
I dont see your screen file attachment

**Comment by the0rist** [comment]
Please, check your inbox of zinzinday@gmail.com

**Comment by zinzinday** [comment]
Please update composer
i was test on my project after insert pix cursor at right of pix.
if your page right to left i think cursor will left of pix

**Comment by the0rist** [comment]
Is it possible to set the cursor below of picture automatically?

**Comment by the0rist** [comment]
Hello.
It's a bug of the redactor core.

On the official demo on site of redactor I can see the same issue.
You can try to insert a picture in an empty redactor window and you'll see
the caret doesn't move below an inserted picture.
