### ISSUE TITLE
Invalid config $uploadDir

### ISSUE THREAD

**Issue by AlaFalaki** [yiidoc/yii2-redactor#33]
Hi,
i followed steps that u said,
but when i want to upload an image, the ajax requests get "500 Internal Server Error" error
and the error is:
message: "Invalid config $uploadDir"
name: "Invalid Configuration"

what is the problem ?

thank you.

**Comment by AlaFalaki** [comment]
there was a problem with uploadDir and uploadURL, got fixed.

**Comment by yanugto** [comment]
how to fix it?

**Comment by AlaFalaki** [comment]
@yanugto
Hi there, this issue is for about 2 years ago, the process of what i've done is a little blury :)

Navigate to the `/vendor/yiidoc/yii2-redactor` folder, and put the upload directory path in the `RedactorModule.php` file.
Simply change `defaultRoute`, `uploadDir`, `uploadUrl` variables. my config file looks like this:

```
public $defaultRoute = 'upload/editor';
public $uploadDir = '../upload/editor';
public $uploadUrl = '/upload/editor';
```

I have created a `upload` directory in my frontend web root.
I hope this will help you...

**Comment by filipajdacic** [comment]
@AlaFalaki  It is not the proper way to fix things....
If you want to upload files in frontend/web than you can do in your config/main.php something like:
```
..
  'uploadDir' => \Yii::getAlias('@frontend') . '/web/uploads/blog',
 'uploadUrl' => '/uploads/blog',
..
```

@yanugto  I have the same problem, check if your path in config is correct. My uploadDir path was not correct and I was getting this error, once when I fixed my uploadDir path everything started to work properly...
