### ISSUE TITLE
empty $_FILES on file/image upload

### ISSUE THREAD

**Issue by romdim** [yiidoc/yii2-redactor#35]
Hello there, very helpful plugin. Cheers!

I have a problem when trying to upload an image or a file.
It makes a post at the designated folder, named /uploads and gets a 301 moved permanent response although it does indeed hit the /uploads/index.php file, which contains the upload.php suggested over here http://imperavi.com/redactor/docs/upload-images/ .
By debugging I can see that there is no $_FILES variable, so an alert comes that says true and I get a 200 response for /uploads/ but nothing more.
No upload is taking place.

Does anyone know what is going wrong?
Thank you very much in advance!

**Comment by romdim** [comment]
After a lot of experimenting I found the solution and wrote it down [here](http://stackoverflow.com/questions/32565812/php-post-file-through-yii2-redactor-text-editor-results-in-empty-files-noth/32566185#32566185)

**Comment by muzammilhassan** [comment]
romdim, I have tried your solution too but nothing happens
