### ISSUE TITLE
How to set the upload dir?

### ISSUE THREAD

**Issue by Yemsheng** [yiidoc/yii2-redactor#44]
The default one is "uploads". How can I set another one?

**Comment by zinzinday** [comment]
Hi,
If your config in file /common/config/main.php not working.
Let's config with file /common/config/bootstrap.php

```
....
\Yii::$container->set('yii\redactor\RedactorModule', [
    'uploadDir' => 'path/to/folder/upload'
    'uploadUrl' => '//yourname.xzy/point/to/folder/upload'
]);
```

**Comment by Yemsheng** [comment]
@zinzinday, thank you
