### ISSUE TITLE
Clues on using this plugin

### ISSUE THREAD

**Issue by digitlou** [yiidoc/yii2-redactor#7]
Hi. Thanks for your effort in this plugin.
I cannot make it work properly.
If I comment clientOptions (in _form.php) it don't reach imageGetJson showing just the field for writing a path for the image, and this works OK.
If I write the path in clientOptions for whowing a 'proper' upload window:
```
    <?php echo $form->field($model, 'post_content')->widget(Redactor::className(),[
    'clientOptions'=>[
    'imageGetJson' => '/redactor/upload/imagejson',
    'imageUpload' => '/uploads', // supposing folder in /frontend/uploads // is it the folder or the action in   controller?
    ......
```
it gives me a 404: 
```
    GET http://yii2test.local:8080/redactor/upload/imagejson 404 (Not Found) jquery.js:8623
OR
    'imageGetJson' => '/redactor/upload/imagejson',
    'imageUpload' => '/redactor/upload/image',
    'clipboardUploadUrl' => '/redactor/upload/clipboard',
    'fileUpload' => '/redactor/upload/file',

    POST http://yii2test.local:8080/redactor/upload/image 404 (Not Found)
```
Please, any clue? I'm working with advanced app (admin/frontend/common). Folder created with 777 permission under /frontend, and reachable (tested) from public access.
Could you invest just fifteen minutes with some minimal guides and a simple example for uploading a file/image?
Do I need to make an action in my controller (although it looks like you have written one)?
Do I need to use it on a proper dedicated field, only for file or image uploading? Now I'm trying to use it inside a textarea.
How can I show uploaded images (just the path)?
Thanks in advance.

**Comment by alexantr** [comment]
I'm using
```php
[
    'imageUpload' => Url::to(['/redactor/upload/image']),
    'fileUpload' => Url::to(['/redactor/upload/file']),
]
```

**Comment by TomTheGeek** [comment]
"Read the docs" is only useful when the docs are complete. A snippet of code but no clue to where it goes is not helpful. There are many places in a file the code could go. Even the readme on the project homepage is incorrect.

**Comment by lisiy50** [comment]
http://sitename/redactor/upload/image returns 404 error. Upload module doesn't work for me to.

**Comment by lisiy50** [comment]
Check the configuration of urlManager rules.

**Comment by zinzinday** [comment]
my :-1:  i have some modify config please review https://github.com/yiidoc/yii2-redactor#configure
